server:
  port: 80
spring:
  session:
    store-type: none
  application:
    name: app-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/test?autoReconnect=true&useSSL=false&characterEncoding=utf-8
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.43.243
    port: 5672
    username: guest
    password: guest
  redis:
    database: 1 #索引（默认为0）
    host: localhost #地址
    port: 6379 #端口号
    pool:
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）

#注册中心
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}
  client:
     serviceUrl:
        defaultZone: http://localhost:9000/eureka

lyc:
  security:
    browser:
      loginPage: /login.html
    code:
      image:
        length: 6
        width: 100
    social:
      filterProcessesUrl: /qqLogin
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
