server:
  port: 7070
spring:
  session:
    store-type: none
  application:
    name: app-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/jtdb?autoReconnect=true&useSSL=false&characterEncoding=utf-8
  jpa:
    show-sql: true


#注册中心
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}
  client:
     serviceUrl:
        defaultZone: http://localhost:9000/eureka

lyc:
  security:
    browser:
      loginPage: /login.html
    code:
      image:
        length: 6
        width: 100
        url: /users,/users/*
